version: "3.8"
services:
  proxy:
    image: nginx:1.19
    environment:
      - KIBANA_ENDPOINT
      - KIBANA_BASIC_AUTH
    ports:
      - 8000:80
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - ./proxy/web:/usr/share/nginx/html
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    volumes:
      - ./grafana:/etc/grafana
    environment:
      GF_LOG_FILTERS: rendering:debug
      GF_DATABASE_TYPE: sqlite3
  renderer:
    image: grafana/grafana-image-renderer:2.0.0
    environment:
      ENABLE_METRICS: 'true'
