branch-defaults:
  default:
    environment: safecastrpt-dev-001
environment-defaults:
  safecastrpt-dev-001:
    branch: null
    repository: null
global:
  application_name: reporting
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
