name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Grafana to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.grafana
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: safecast/reporting2/grafana
          tag_with_ref: true
          tag_with_sha: true
      - name: Set container sha
        run: echo "::set-env name=CONTAINER_SHA::$(git rev-parse --short=7 HEAD)"
      - name: Update built images
        run: |
          sed -i \
            "s|docker.pkg.github.com/safecast/reporting2/grafana:latest|docker.pkg.github.com/safecast/reporting2/grafana:sha-${CONTAINER_SHA}|"\
            Dockerrun.aws.json
      - uses: actions/upload-artifact@v2
        with:
          name: sha-${{ env.CONTAINER_SHA }}
          path: |
            .
            !.git
            !.gitignore
            !.ebignore
            !.github
