name: Main

on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Grafana to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.grafana
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: safecast/reporting2/grafana
          tag_with_ref: true
          tag_with_sha: true
      - name: Set container sha
        run: echo "::set-env name=CONTAINER_SHA::$(git rev-parse --short=7 HEAD)"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Create application bundle
        uses: ./.github/bundle-application
        with:
            app: reporting
            s3_bucket: elasticbeanstalk-us-west-2-985752656544
            authentication_key: .docker/config.json.auths
            container_images: |
              { "grafana": "docker.pkg.github.com/safecast/reporting2/grafana:sha-${{ env.CONTAINER_SHA }}" }
