name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Push Grafana to GitHub Packages
#        uses: docker/build-push-action@v1
#        with:
#          dockerfile: Dockerfile.grafana
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: safecast/reporting2/grafana
#          tag_with_ref: true
#          tag_with_sha: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: maybe python
        run: python --version
